progress: 100

announces:
  announce1:
    title: "Test Line1"
    bar:
      color: GREEN
      style: SOLID
    duration: 2
  announce2:
    title: "Test Line1"
    bar:
      color: GREEN
      style: SOLID
    duration: 2